root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.eslint.json'
  tsconfigRootDir: ./
extends: 
  - 'moon'
  - 'moon/node'
rules:
  'sort-keys': 'off'
  'no-magic-numbers': 'off'
  'import/no-unresolved': 'off'
  'import/no-useless-path-segments': 'off'
  '@typescript-eslint/no-parameter-properties': 'off'
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-extraneous-class': 'off'
